# Tensor

Here are the basic types of tensors along with their dimensions and some of their common operations:

1. Scalar (0D Tensor):
    A scalar tensor is a single value with no dimensions.
    Example: 5, -3.14
    Operations: Scalars are used as the base elements for mathematical operations.

2. 1D Tensor (Vector):
    A 1D tensor, often referred to as a vector, has one dimension.
    Example: [1, 2, 3, 4, 5]
    Operations: You can perform vector addition, subtraction, element-wise multiplication, and more.

3. 2D Tensor (Matrix):
    A 2D tensor, or matrix, has two dimensions: rows and columns.
    Example:
    [
      [1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]
    ]
    Operations: Matrix multiplication, element-wise operations, transposition, and more.

3. 3D Tensor:
    A 3D tensor has three dimensions: depth, rows, and columns.
    Example:
    [
      [
        [1, 2, 3],
        [4, 5, 6]
      ],
      [
        [7, 8, 9],
        [10, 11, 12]
      ]
    ]
    Operations: Used for operations involving 3D data, such as RGB images or time series data.

Common operations on tensors include:
1. Element-wise Operations: Operations performed independently on each element of a tensor.
2. Matrix Multiplication: Computing the dot product of two matrices.
3. Transpose: Flipping a matrix along its main diagonal.
4. Indexing and Slicing: Accessing specific elements or sub-tensors within a tensor.
5. Reshaping: Changing the shape of a tensor while maintaining the same number of elements.
6. Reduction Operations: Calculating statistics like sum, mean, min, max along certain dimensions.
7. Broadcasting: Implicitly expanding tensors of smaller shape to match the shape of larger tensors.

In [36]:
#2d tensor
x = torch.ones(100,2)
print(x.shape)
print(x[1])

y = torch.ones(2,2)
print(y.shape)
print(y[1])

torch.Size([100, 2])
tensor([1., 1.])
torch.Size([2, 2])
tensor([1., 1.])


In [27]:
import torch
x = torch.arange(-3,3,0.1)
print(x)
x = x.view(-1,1)
print(x)

tensor([-3.0000e+00, -2.9000e+00, -2.8000e+00, -2.7000e+00, -2.6000e+00,
        -2.5000e+00, -2.4000e+00, -2.3000e+00, -2.2000e+00, -2.1000e+00,
        -2.0000e+00, -1.9000e+00, -1.8000e+00, -1.7000e+00, -1.6000e+00,
        -1.5000e+00, -1.4000e+00, -1.3000e+00, -1.2000e+00, -1.1000e+00,
        -1.0000e+00, -9.0000e-01, -8.0000e-01, -7.0000e-01, -6.0000e-01,
        -5.0000e-01, -4.0000e-01, -3.0000e-01, -2.0000e-01, -1.0000e-01,
        -2.3842e-08,  1.0000e-01,  2.0000e-01,  3.0000e-01,  4.0000e-01,
         5.0000e-01,  6.0000e-01,  7.0000e-01,  8.0000e-01,  9.0000e-01,
         1.0000e+00,  1.1000e+00,  1.2000e+00,  1.3000e+00,  1.4000e+00,
         1.5000e+00,  1.6000e+00,  1.7000e+00,  1.8000e+00,  1.9000e+00,
         2.0000e+00,  2.1000e+00,  2.2000e+00,  2.3000e+00,  2.4000e+00,
         2.5000e+00,  2.6000e+00,  2.7000e+00,  2.8000e+00,  2.9000e+00])
tensor([[-3.0000e+00],
        [-2.9000e+00],
        [-2.8000e+00],
        [-2.7000e+00],
        [-2.6000e+00],
        

### Derivatives of tensor

In [23]:
import torch
import matplotlib.pylab as plt

this requires_grad parameter will tell pytorch that we would be using evaluating functions and derivatives of x using this value of x.

In [14]:
x = torch.tensor(2.0, requires_grad= True)

In [4]:
y=x**2

In [5]:
y.backward()

In [7]:
x.grad

tensor(4.)

In [8]:
z = x**2 + 2*x + 1

In [9]:
z.backward()

In [10]:
x.grad

tensor(10.)

### Partial Derivatives

In [16]:
u = torch.tensor(1.0, requires_grad= True)
v = torch.tensor(2.0, requires_grad= True)

In [17]:
f= u*v + u**2

In [18]:
f.backward()

In [19]:
u.grad

tensor(4.)

In [20]:
v.grad

tensor(1.)

### Differentiation wrt x at multiple values

In [26]:
x= torch.linspace(-10, 10, 20, requires_grad= True)
y= torch.sum(x**2)
y.backward()
x.grad

tensor([-20.0000, -17.8947, -15.7895, -13.6842, -11.5789,  -9.4737,  -7.3684,
         -5.2632,  -3.1579,  -1.0526,   1.0526,   3.1579,   5.2632,   7.3684,
          9.4737,  11.5789,  13.6842,  15.7895,  17.8947,  20.0000])

# Dataset and Dataloader

## Dataset:

### Dataset Class:

**1. Data Representation:**
The primary role of the Dataset class is to provide an interface for representing your data. It encapsulates your data points and makes them accessible in a structured manner. This includes loading and storing individual data points.

**2. Custom Data Loading:**
The Dataset class allows you to implement custom data loading and preprocessing logic. You can define how to read data from files, apply transformations, and prepare data points for training or evaluation.

**3. Data Access by Index:**
It enables you to access individual data points using their indices. The \_\_getitem\_\_() method in your custom dataset class defines how a specific data point is accessed.

**4. Size Information:**
The \_\_len\_\_() method in your Dataset class returns the total number of data points in the dataset, providing size information.

### DataLoader Class:
**1. Batching:**
The DataLoader class takes care of dividing your dataset into smaller batches. Batching is essential for efficient training, as models often learn better and faster when trained on batches of data rather than individual data points.

**2. Shuffling:**
It can shuffle the data within each epoch to prevent the model from learning any order-based patterns. Shuffling helps to ensure randomness and prevents biases during training.

**3. Parallel Loading:**
The DataLoader class can load and preprocess batches of data in parallel, leveraging multiple CPU cores. This accelerates the data loading process, especially for large datasets.

**4. Iterating Through Batches:**
It provides an iterator interface that allows you to easily loop through batches of data. You can use a for loop to iterate through batches in your training or evaluation loop.

**5. Convenient Usage:**
The DataLoader abstracts away the complexity of batching, shuffling, and parallel loading. It provides a convenient way to access data in a format suitable for training and evaluation.

In summary, the Dataset class focuses on representing your data and providing customized data loading logic, while the DataLoader class handles the mechanics of batching, shuffling, parallel loading, and iteration. Together, they provide an efficient and convenient way to work with large datasets during machine learning model training and evaluation.

### Example of creating dataset and applying single transform with is not mentioned in dataset class

In [8]:
import torch
from torch.utils.data import Dataset

# dataset
class toy_set(Dataset):
    def __init__(self,length=100,transform=None):
        self.x= 2 * torch.ones(length,2)
        self.y= torch.ones(length,1)
        self.len= length
        self.transform= transform
    
    def __getitem__(self,index):
        sample= self.x[index],self.y[index]
        if self.transform:
            sample= self.transform(sample)
        return sample
    
    def __len__(self):
        return self.len
    
#transform
class add_mult(object):
    def __init__(self,addx=1,muly=1):
        self.addx=addx
        self.muly=muly
    def __call__(self,sample):
        x=sample[0]
        y=sample[1]
        x=x+self.addx
        y=y*self.muly
        sample=x,y
        return sample

#create dataset object
dataset= toy_set()
#create transform object
a_m= add_mult()
#apply transform to a datapoint
print(dataset[0])
x_,y_=a_m(dataset[0])
print(x_,y_)



    

(tensor([2., 2.]), tensor([1.]))
tensor([3., 3.]) tensor([1.])


### Example of creating dataset and applying single transform automatically when we access a datapoint

In [11]:
import torch
from torch.utils.data import Dataset

# dataset
class toy_set(Dataset):
    def __init__(self,length=100,transform=None):
        self.x= 2 * torch.ones(length,2)
        self.y= torch.ones(length,1)
        self.len= length
        self.transform= transform
    
    def __getitem__(self,index):
        sample= self.x[index],self.y[index]
        if self.transform:
            sample= self.transform(sample)
        return sample
    
    def __len__(self):
        return self.len
    
#transform
class add_mult(object):
    def __init__(self,addx=1,muly=1):
        self.addx=addx
        self.muly=muly
    def __call__(self,sample):
        x=sample[0]
        y=sample[1]
        x=x+self.addx
        y=y*self.muly
        sample=x,y
        return sample

#transform object
a_m= add_mult()

#dataset object
# '_' indicates transform have been applied 
dataset_= toy_set(transform=a_m)
print(dataset_[0])


(tensor([3., 3.]), tensor([1.]))


### Transform Compose: to apply several transform from outside when we access a datapoint

In [13]:
import torch
from torch.utils.data import Dataset

# dataset
class toy_set(Dataset):
    def __init__(self,length=100,transform=None):
        self.x= 2 * torch.ones(length,2)
        self.y= torch.ones(length,1)
        self.len= length
        self.transform= transform
    
    def __getitem__(self,index):
        sample= self.x[index],self.y[index]
        if self.transform:
            sample= self.transform(sample)
        return sample
    
    def __len__(self):
        return self.len

class add_mult(object):
    def __init__(self,addx=1,muly=1):
        self.addx=addx
        self.muly=muly
    def __call__(self,sample):
        x=sample[0]
        y=sample[1]
        x=x+self.addx
        y=y*self.muly
        sample=x,y
        return sample

class mult(object):
    def __init__(self,mul=100):
        self.mul=mul
    def __call__(self,sample):
        x=sample[0]
        y=sample[1]
        x=x*self.mul
        y=y*self.mul
        sample=x,y
        return sample

from torchvision import transforms

#create a chain of transform
data_transform = transforms.Compose([add_mult(),mult()])

#create dataset object
dataset= toy_set()
print(dataset[0])
x_,y_= data_transform(dataset[0])
print(x_,y_)

(tensor([2., 2.]), tensor([1.]))
tensor([300., 300.]) tensor([100.])


### Transform Compose: to apply several transform automatically when we access a datapoint

In [15]:
import torch
from torch.utils.data import Dataset

# dataset
class toy_set(Dataset):
    def __init__(self,length=100,transform=None):
        self.x= 2 * torch.ones(length,2)
        self.y= torch.ones(length,1)
        self.len= length
        self.transform= transform
    
    def __getitem__(self,index):
        sample= self.x[index],self.y[index]
        if self.transform:
            sample= self.transform(sample)
        return sample
    
    def __len__(self):
        return self.len

class add_mult(object):
    def __init__(self,addx=1,muly=1):
        self.addx=addx
        self.muly=muly
    def __call__(self,sample):
        x=sample[0]
        y=sample[1]
        x=x+self.addx
        y=y*self.muly
        sample=x,y
        return sample

class mult(object):
    def __init__(self,mul=100):
        self.mul=mul
    def __call__(self,sample):
        x=sample[0]
        y=sample[1]
        x=x*self.mul
        y=y*self.mul
        sample=x,y
        return sample

from torchvision import transforms

#create a chain of transform
data_transform = transforms.Compose([add_mult(),mult()])

#create dataset object and pass transforms object
dataset_= toy_set(transform= data_transform)
print(dataset_[0])


(tensor([300., 300.]), tensor([100.]))


# torchvision

torchvision is a sub-library of PyTorch that provides various utilities and tools for working with computer vision tasks. One of the key functionalities of torchvision is to provide pre-built datasets and data transformation mechanisms that are commonly used in computer vision tasks. The torchvision.datasets module offers access to several popular datasets, and the torchvision.transforms module provides transformations for data preprocessing.

### torchvision dataset:

One of the significant use cases for torchvision.datasets is to provide standardized datasets that enable researchers and practitioners to compare different machine learning models in a consistent manner. These datasets act as a common ground for evaluating the performance of various algorithms and models on the same data, making comparisons more meaningful and fair.

When comparing models, using the same dataset allows researchers and practitioners to focus on the differences in algorithms and architectures rather than variations in the datasets themselves. This standardized approach enhances the credibility of the comparison and helps the community identify which methods perform better under specific conditions.

For example, when comparing image classification models, you might use datasets like MNIST, CIFAR-10, or ImageNet to evaluate how different models perform on different scales of complexity and diversity in the dataset. By using well-established datasets, you can ensure that the differences observed in model performance are likely due to the model itself and not the idiosyncrasies of the data.

Using torchvision.datasets for model comparison also streamlines the process, as you can readily access and preprocess these datasets without needing to manually curate, format, and preprocess the data yourself. This is especially valuable when you want to focus on the model's architecture, training process, and evaluation metrics.

### torchvision dataloader

When it comes to data loaders in torchvision, they are used to efficiently load and preprocess data from datasets for training, validation, and testing purposes. Data loaders make it easier to handle large datasets and manage memory effectively, while also allowing for various data augmentation and preprocessing techniques.

Here are the main features and uses of torchvision data loaders:

**1. Batching:** Data loaders automatically batch the data, which means that instead of loading the entire dataset at once, they load a small batch of samples (images and labels) into memory. This is essential for training neural networks efficiently, as it enables batch processing, which can significantly speed up training.

**2. Shuffling:** Data loaders can shuffle the dataset before each epoch during training. Shuffling the data helps prevent the model from memorizing the order of samples and enhances its generalization ability.

**3. Parallel Loading:** Data loaders can load batches in parallel using multiple workers. This helps to utilize the CPU cores efficiently and reduces the time spent waiting for data loading, which can speed up training.

**4. Data Augmentation:** torchvision provides various data augmentation techniques through the transforms module. You can apply transformations like random cropping, resizing, flipping, and color jittering to augment your dataset, which can improve the model's ability to generalize.

**5. Normalization:** You can apply normalization to the dataset using the transforms.Normalize transformation. Normalization ensures that pixel values have a consistent scale, which can help stabilize the training process.

**6. Custom Dataset Support:** In addition to pre-built datasets, you can also use data loaders with your custom datasets by creating a custom dataset class that adheres to the torch.utils.data.Dataset interface.

In summary, torchvision data loaders are a crucial tool for efficiently loading, preprocessing, and augmenting datasets for training and evaluation in computer vision tasks. They provide an effective way to manage memory usage, parallelize data loading, and apply various preprocessing techniques to enhance the performance of machine learning models.

### Download MNSIT pre- built dataset and Create dataloader

In [23]:
import torch
from torchvision import transforms
from torchvision.datasets import MNIST
from torch.utils.data import DataLoader

#Define data transformations
transform = transforms.Compose([
    transforms.ToTensor(),
])

#Download MNSIT dataset
mnist_train_dataset = MNIST(root='./resources/data', train=True, download=True, transform=transform)
mnist_test_dataset = MNIST(root='./resources/data', train=False, download=True, transform=transform)

#Create data loaders
batch_size=64
train_loader= DataLoader(mnist_train_dataset, batch_size=batch_size, shuffle=True)
test_loader= DataLoader(mnist_test_dataset, batch_size=batch_size, shuffle=False)



## Custom module in pytorch

In PyTorch, a custom module is typically a class that inherits from the torch.nn.Module base class. This allows you to define your own neural network architectures, encapsulate parameters, and create complex operations. Here's a basic example of creating a custom module:

In [29]:
import torch
import torch.nn as nn

class CustomModule(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(CustomModule, self).__init__()
        
        self.layer1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(hidden_size, output_size)
    
    def forward(self, x):
        x = self.layer1(x)
        x = self.relu(x)
        x = self.layer2(x)
        return x

#The __init__ method sets up the layers, and the forward method defines the forward pass of the network.

#Remember to always call the parent class's __init__ method using super() to properly initialize the module.

# Instantiate the custom module
input_size = 10
hidden_size = 20
output_size = 5
model = CustomModule(input_size, hidden_size, output_size)

# Create some dummy input data
dummy_input = torch.randn(32, input_size)

# Pass the input through the model
output = model(dummy_input)
print(output)

tensor([[-0.0197,  0.0136,  0.3860,  0.3506, -0.4686],
        [-0.1528, -0.4839,  0.4383,  0.2422, -0.3714],
        [-0.3400, -0.6243,  0.6892,  0.2933, -0.4380],
        [-0.0349,  0.0462,  0.2903,  0.2954, -0.2494],
        [ 0.2567, -0.1921,  0.0096, -0.0072, -0.1223],
        [ 0.0458, -0.3592,  0.2569,  0.4142, -0.2592],
        [ 0.3067,  0.1053,  0.1666,  0.0559, -0.0421],
        [ 0.0919, -0.0995,  0.1116,  0.2467, -0.1492],
        [-0.0205, -0.3303,  0.2824,  0.3910, -0.2438],
        [-0.1113, -0.8372,  0.2890,  0.3676, -0.4409],
        [-0.0110, -0.0063,  0.3826,  0.0114, -0.1678],
        [-0.0869, -0.2933,  0.4273, -0.1934, -0.0405],
        [ 0.1212, -0.2647,  0.4032,  0.5093, -0.1859],
        [ 0.1697, -0.2908,  0.2509,  0.0557, -0.0071],
        [ 0.0758, -0.0367,  0.3924,  0.0114, -0.1779],
        [-0.0682, -0.3100,  0.3005,  0.2177, -0.3292],
        [ 0.1382, -0.4229,  0.3518,  0.4382, -0.2012],
        [ 0.2454, -0.2646,  0.3053,  0.2587, -0.0134],
        [ 

## Gradient Descent

It is used to find the minimum of a function, it can be applied to a function with multiple dimensions.

1)what should be learning rate: 
  if we choose the learning rate as high, sometime we miss the minima. if we select the learning rate too low, then the  number
  of iteration will increase.

2)when to stop the gradient discent: 
   see if loss starts increasing. record a few iterations of gradient descent  and record the results in the table.

## Cost/Loss

In order to find the best values for the parameters of a model, we need to find how good our model is, a quantity that is near zero when our model provides a good estimate and large when our model is bad, we call this quantity the loss/cost.

## Stocastic Gradient Descent

In SGD, instead of using the entire dataset for each iteration, only a single random training example (or a small batch) is selected to calculate the gradient and update the model parameters. This random selection introduces randomness into the optimization process, hence the term “stochastic” in stochastic Gradient Descent.

The problem with stocastic gradient descent is that the value of cost/loss fluctuate rapildy with each iteration.

In SGD, no. of epochs is not same as number of iterations.

### Example: performing stocastic gradient descent using dataset and dataloader

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader

# Set random seed
torch.manual_seed(1)

w= torch.tensor(-15.0, requires_grad=True)
b= torch.tensor(-10.0, requires_grad=True)

def forward(x):
    y=w*x+b
    return y

def criterion(yaht,y):
    return torch.mean((yhat-y)**2)

class Data(Dataset):
    def __init__(self):
        self.x= torch.arange(-3,3,0.1).view(-1,1)
        self.y= 3*self.x+1
        self.len= self.x.shape[0]
    
    def __getitem__(self,index):
        return self.x[index],self.y[index]
    
    def __len__(self):
        return self.len
    
dataset= Data()

trainloader= DataLoader(dataset=dataset, batch_size=1)

lr= 0.1
LOSS=[]

for epoch in range(4):
    total=0
    for x,y in trainloader:
        yhat= forward(x)
        loss= criterion(yhat,y)
        loss.backward()
        
        #update the parameters
        w.data -= lr * w.grad.data
        b.data -= lr * b.grad.data
        
        w.grad.data.zero_()
        b.grad.data.zero_()
        total+= loss.item()
    LOSS.append(total)

print(LOSS)
#show error reduced after each epoch
import matplotlib.pyplot as plt
%matplotlib inline

# Create a plot
plt.plot(LOSS, marker='o', linestyle='-')

# Add labels and title
plt.xlabel('loss')
plt.ylabel('epoch')
plt.title('loss v/s epoch graph')

# Display the plot
plt.show()
    

[6476.763609051704, 1225.0185958952643, 291.4723268855596, 69.35072039815714]


## Mini-batch Gradient Descent

It has many advantages, one important one is that it will allow you to process larger datasets, that you will not be able to fit into memory, because it splits up the dataset into smaller samples.

In Mini-BGD, the relationship between batch size, number of iterations and epochs is a little more complicated.

## Hyper Parameters

## torch.optim

### Example: Linear Regression 1D: Training two parameters with mini-batch gradient descent using dataset, dataloader,   torch.optim.SGD and torch.nn.MSELoss