# Tensor

Here are the basic types of tensors along with their dimensions and some of their common operations:

1. Scalar (0D Tensor):
    A scalar tensor is a single value with no dimensions.
    Example: 5, -3.14
    Operations: Scalars are used as the base elements for mathematical operations.

2. 1D Tensor (Vector):
    A 1D tensor, often referred to as a vector, has one dimension.
    Example: [1, 2, 3, 4, 5]
    Operations: You can perform vector addition, subtraction, element-wise multiplication, and more.

3. 2D Tensor (Matrix):
    A 2D tensor, or matrix, has two dimensions: rows and columns.
    Example:
    [
      [1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]
    ]
    Operations: Matrix multiplication, element-wise operations, transposition, and more.

3. 3D Tensor:
    A 3D tensor has three dimensions: depth, rows, and columns.
    Example:
    [
      [
        [1, 2, 3],
        [4, 5, 6]
      ],
      [
        [7, 8, 9],
        [10, 11, 12]
      ]
    ]
    Operations: Used for operations involving 3D data, such as RGB images or time series data.

Common operations on tensors include:
1. Element-wise Operations: Operations performed independently on each element of a tensor.
2. Matrix Multiplication: Computing the dot product of two matrices.
3. Transpose: Flipping a matrix along its main diagonal.
4. Indexing and Slicing: Accessing specific elements or sub-tensors within a tensor.
5. Reshaping: Changing the shape of a tensor while maintaining the same number of elements.
6. Reduction Operations: Calculating statistics like sum, mean, min, max along certain dimensions.
7. Broadcasting: Implicitly expanding tensors of smaller shape to match the shape of larger tensors.

In [36]:
#2d tensor
x = torch.ones(100,2)
print(x.shape)
print(x[1])

y = torch.ones(2,2)
print(y.shape)
print(y[1])

torch.Size([100, 2])
tensor([1., 1.])
torch.Size([2, 2])
tensor([1., 1.])


### Derivatives of tensor

In [23]:
import torch
import matplotlib.pylab as plt

this requires_grad parameter will tell pytorch that we would be using evaluating functions and derivatives of x using this value of x.

In [14]:
x = torch.tensor(2.0, requires_grad= True)

In [4]:
y=x**2

In [5]:
y.backward()

In [7]:
x.grad

tensor(4.)

In [8]:
z = x**2 + 2*x + 1

In [9]:
z.backward()

In [10]:
x.grad

tensor(10.)

### Partial Derivatives

In [16]:
u = torch.tensor(1.0, requires_grad= True)
v = torch.tensor(2.0, requires_grad= True)

In [17]:
f= u*v + u**2

In [18]:
f.backward()

In [19]:
u.grad

tensor(4.)

In [20]:
v.grad

tensor(1.)

### Differentiation wrt x at multiple values

In [26]:
x= torch.linspace(-10, 10, 20, requires_grad= True)
y= torch.sum(x**2)
y.backward()
x.grad

tensor([-20.0000, -17.8947, -15.7895, -13.6842, -11.5789,  -9.4737,  -7.3684,
         -5.2632,  -3.1579,  -1.0526,   1.0526,   3.1579,   5.2632,   7.3684,
          9.4737,  11.5789,  13.6842,  15.7895,  17.8947,  20.0000])